### ISSUE TITLE
"S-R Flip Flop" is actually a Latch

### ISSUE THREAD

**Issue by Rylander77** [OpenCircuits/OpenCircuits#103]
Latches (with enable) are designed to respond to a logic high state of the enable, which is what the current SR FF does. 

A D latch using this current "SR FF" is demonstrated as follows:
![image](https://user-images.githubusercontent.com/20091001/45831168-b0c74600-bccc-11e8-82e7-5f9dc57e6661.png)
which demonstrates properties properties of a latch.

Additionally, this S-R latch does not exhibit meta-stability: as shown here:
![image](https://user-images.githubusercontent.com/20091001/45831451-6a261b80-bccd-11e8-9e4d-4a6b9c715028.png)

**Comment by Rylander77** [comment]
A FF exhibits edge triggering: meaning at one "edge" of the clock signal (going from high to low or low to high) is when the data input can be interpreted. This is much more accurate from a timing standpoint, so long as your clock is not faster than the delay of a gate, as a cascaded NOT gate and a second latch are used to achieve positive or negative edge triggering. 

A poisitive edge triggered D FF can be seen below:
![image](https://user-images.githubusercontent.com/20091001/45832732-c179bb00-bcd0-11e8-9167-71636f45eba8.png)

The data input (just D, the switch) only affects the state of the output LED at the positive edge of the clock, when the clock goes from low to high.

**Comment by Schmaj** [comment]
Changed to SR Latch. Will implement SR FF later.
