### ISSUE TITLE
Add 9, 14, and 16 segment displays

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#127]
https://en.wikipedia.org/wiki/Sixteen-segment_display

**Comment by nprisament** [comment]
I think we only need the 16 segment display instead of also 9 and 14, because both of them are essentially the same as 16 but with certain segments either banded together or not implemented

**Comment by LeonMontealegre** [comment]
@nprisament 
I think it would be useful to have all combinations and have a general N-Segment-Display component and have the option to increase/decrease the input count

**Comment by nprisament** [comment]
ahh, so there would be a single "segment display" component where the input count determines the number of segments?

**Comment by LeonMontealegre** [comment]
yeah something like that
