### ISSUE TITLE
Reimplement Test Mode

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#141]

**Comment by nprisament** [comment]
what does this bug mean?

**Comment by LeonMontealegre** [comment]
There's a little hamburger menu icon in the top-top left of the screen.
Clicking it should open another side menu with lots of future plans.
One of the buttons on it was a toggle for something called "Test mode" which disabled the Place Component menu, and the ability to move, select, or change the circuit - only interact with buttons and such.

For some reason it required clicking the toggle twice initially to work but idk if this will still apply when I get around to reimplementing it.
