### ISSUE TITLE
Change side menu hamburger icon

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#144]
Change from a hamburger to something like >> 

Similar to desmos (https://www.desmos.com/calculator)

**Comment by baxtea** [comment]
I think there are more descriptive icons. Perhaps a + sign to indicate the addition of components, or something like the [git fork icon](https://livablesoftware.com/wp-content/uploads/2017/11/code-fork-icon-64988.png) for circuitry imagery, or some combination of the two?
