### ISSUE TITLE
Adding all the components back

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#154]
All the flip-flops, gates, keyboard, encoder, labels, etc.

**Comment by nprisament** [comment]
- [ ] constant inputs
- [ ] button
- [ ] clock
- [ ] keyboard
- [ ] 7 segment display
- [ ] latches
- [ ] label
- [ ] multiplexer
- [ ] encoder

**Comment by LeonMontealegre** [comment]
I think the keyboard is a very low-priority component so I'm gonna mark this as closed for now
