### ISSUE TITLE
Add side panel w/ example circuits

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#16]
Something like Desmos' example graphs

**Comment by LeonMontealegre** [comment]
A lot of progress made from Branch #23, still needs work once database layer is in (#19 )

**Comment by nprisament** [comment]
if this is implemented we must make sure they are loaded like other circuits and do not erase the current progress

**Comment by LeonMontealegre** [comment]
Yeah they will be loaded like loading a circuit from your computer (via XML) and will ask if you want to overwrite your current circuit if it isn't saved
