### ISSUE TITLE
WirePorts

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#168]
Re-add "WirePorts".

Basically, they are very simple Components that are used to split wires and are rendered as a single port.

Example:
<img width="533" alt="screen shot 2019-02-05 at 11 18 22 am" src="https://user-images.githubusercontent.com/29997057/52287234-c5347400-2937-11e9-9859-d681f22b16b9.png">

Try to write simple unit tests before implementing them to make sure they act appropriately.

Functionally, they act just like BUFGates.

For implementing them they'd be Component with exactly 1 input and output.

For rendering, you'd probably want to just put an if-statement before the rendering of the IOPorts in the ComponentRenderer.ts checking if the object is a WirePort and if it is then have a specific rendering process for them and 'return' early.
Or, potentially a better solution would be to set the origin/target of each input/output port to be at the origin of the local transform and the rendering of the port should just automatically happen but it could cause some rendering issues.

**Comment by nprisament** [comment]
#177

**Comment by LeonMontealegre** [comment]
Don't close issues until the PR has been merged please

**Comment by nprisament** [comment]
> Don't close issues until the PR has been merged please
got it
