### ISSUE TITLE
ICs

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#190]

**Comment by nprisament** [comment]
I think this is the same as #63

**Comment by nprisament** [comment]
Also, one interesting problem is figuring out how to identify ICs in the system as to prevent something like having an IC within itself or two ICs that are codependent

**Comment by LeonMontealegre** [comment]
@nprisament 
Nope #63 is about exporting ICs and is a way long term thing - this is about reimplementing ICs in the refactor which is what I'm currently working on.

Also, ICs can be put inside other ones and that's totally okay so I don't think there's much of a problem. When you create an IC you have to select the components that are being used within it so you can't use one within itself because it already needs to be there and then a new one is created.
