### ISSUE TITLE
Fix compatibility issues

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#214]
There are a lot of things wrong with Firefox and probably IE, Edge, etc.

**Comment by nprisament** [comment]
I am of the opinion that its not worth the time or effort to optimize for IE.

**Comment by LeonMontealegre** [comment]
Firefox is a lot more important.
Also old versions of Chrome (<=42)

**Comment by baxtea** [comment]
I think this can be closed now? It's still broken on Edge, but I don't know of any remaining problems with Firefox.
