### ISSUE TITLE
"Are you sure you want exit" Popup

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#233]
For unsaved circuits

**Comment by nprisament** [comment]
there seem to be two primary ways to implement this, either a mouseout event (the mouse left the window) or an onbeforeunload event (but this is known to be disabled by default in some browsers, eg firefox) on the document / window. Alternatively, we could use both of these methods.

**Comment by nprisament** [comment]
The popup could be a view like the loading screen

**Comment by LeonMontealegre** [comment]
This has already been implemented

// Prompt for exit
window.onbeforeunload = function(e) {
    if (!saved) {
        var dialogText = "You have unsaved changes.";
        e.returnValue = dialogText;
        return dialogText;
    }
};

Just gotta find a place to put it and store the "saved" variable. Probably in Exporter idk.
