### ISSUE TITLE
Selection of Ports

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#238]
Ports should be allowed to be selected through a selection box

![ports](https://user-images.githubusercontent.com/29997057/54562512-8a454780-499d-11e9-82c2-8fb7a273deab.gif)

**Comment by nprisament** [comment]
would this apply to the ports on a wireport?

**Comment by LeonMontealegre** [comment]
@nprisament  Wireports don't have visible ports (or at least they shouldn't). They're objects that can be normally selected.

**Comment by nprisament** [comment]
@LeonMontealegre with my implementation right now, they are just an input and output port that are rendered on top of each other. I am pretty sure this is how they were implemented before. They aren't a lack of port, they are entirely port (although they should still be selectable like a component right now).
