### ISSUE TITLE
Input count module should be capped by selections

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#283]
Currently, it's just set to min=2, max=8 in the HTML.
Should change as the selections change to match the min/max inputs of the selections

**Comment by baxtea** [comment]
What are the min/max port counts for each component type? I don't see anything like this in the TS code base.

**Comment by LeonMontealegre** [comment]
@baxtea 
Components have a "inputPortCount" and an "outputPortCount" field which are ClampedValues which are values that have a min and a max
