### ISSUE TITLE
Refreshing site doesn't update TS code!

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#332]
Go server appears to cache everything and so when I make changes to the TS, I have to restart and rebuild the go-server to see my TS changes!

If I only refresh once per change it appears to not be a problem.

To reproduce:

1. Launch go server
2. Go to your local OpenCircuits
3. Refresh a bunch of times
4. Make TS code changes
5. Refresh page
6. Go console shows that the Bundle was not reloaded and the changes are not present

**Comment by KevinMackenzie** [comment]
The default static file handler for gin doesn't have any cache busting strategy; we need to add something that will force the browser to pull the new version.
