### ISSUE TITLE
Add status indicators for remote operations

### ISSUE THREAD

**Issue by KevinMackenzie** [OpenCircuits/OpenCircuits#392]
Any operation that interacts with the backend should have some sort of status bar, message, progress bar, or any other visual indicator whether the operation is in-process, successful, or failed.

An operation of any length that will affect the user experience should let the user know the operation is in progress and when it completes, but if it does not affect the user, then it can be more discrete.

**Comment by LeonMontealegre** [comment]
This is done for saving through #629 .
Still need something for loading a circuit and logging in
