### ISSUE TITLE
EE wire deletion causes error for new wire creation

### ISSUE THREAD

**Issue by delaneyaqua** [OpenCircuits/OpenCircuits#429]
To recreate bug:
Draw a wire between two elements
Delete wire
Start drawing a new wire, but don't connect the second end to anything (click anywhere)
The first wire should reappear

**Comment by LeonMontealegre** [comment]
Does this apply for digital as well??

**Comment by delaneyaqua** [comment]
no

**Comment by Robert-Hammond** [comment]
Looks like this was fixed 7 months ago, I was unable to repro this bug so I'm gonna close this issue now.
