### ISSUE TITLE
IC Cullbox on Creator is incorrect

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#470]

**Comment by Robert-Hammond** [comment]
Can you describe the problem in further detail please?

**Comment by LeonMontealegre** [comment]
To reproduce:
1) Turn on `DEBUG_CULLBOXES` by setting it to true in `app/core/ts/utils/Constants.ts`
2) Create IC-able circuit:
![Screen Shot 2020-08-18 at 5 29 28 PM](https://user-images.githubusercontent.com/29997057/90567821-c1aeb980-e178-11ea-8e54-f1e4723c4928.png)
3) Create IC:
![Screen Shot 2020-08-18 at 5 29 35 PM](https://user-images.githubusercontent.com/29997057/90567708-962bcf00-e178-11ea-9517-adc09f23743f.png)
4) Resize IC
![Screen Shot 2020-08-18 at 5 29 42 PM](https://user-images.githubusercontent.com/29997057/90567725-9b891980-e178-11ea-8bac-4668c34546ef.png)


Notice how the cullbox (highlighted in green) is incorrect for the re-sized IC.

However, when created, it is correct.
![Screen Shot 2020-08-18 at 5 31 40 PM](https://user-images.githubusercontent.com/29997057/90567779-b22f7080-e178-11ea-9686-fb98fce75fbb.png)
