### ISSUE TITLE
Typing nonsense into input count causes display bug

### ISSUE THREAD

**Issue by GarrettShorr** [OpenCircuits/OpenCircuits#475]
Try typing letters or other invalid input into the input count of a gate, close it, and then upon re-opening the selection popup, a dash is there instead of the actual current count.

**Comment by Robert-Hammond** [comment]
Also, you type the letter 'e' into the input count and some components (i.e. this encoder) will just disappear.
![image](https://user-images.githubusercontent.com/53544605/78402263-e3d7de80-75bf-11ea-81c2-f9b9bc9f5ae9.png)

**Comment by Robert-Hammond** [comment]
Also if you try to give a decoder more than 8 inputs this happens: 
![image](https://user-images.githubusercontent.com/53544605/78408931-02dd6d00-75ce-11ea-9c08-530e37f5811a.png)
