### ISSUE TITLE
Cutting doesn't render after

### ISSUE THREAD

**Issue by gshorrSPHS** [OpenCircuits/OpenCircuits#477]
Selecting the item and doing cmd+x does cut the object, but only after you deselect it. In the following video, the first two times were done with the keyboard shortcut. The contextual menu did not work at all. This is on the published beta version.

http://youtu.be/eOLlDIjuswE?hd=1

**Comment by LeonMontealegre** [comment]
What's happening is that it just hasn't rendered that you cut it, so if you scroll or move around after cutting, then it'll show as disappeared. Gotta fix this yep. Also yeah context menu is a shell, see #361
