### ISSUE TITLE
Mobile bugs

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#492]
- [x] When keyboard comes up, the canvas doesn't resize correctly when the keyboard goes back down.
- [ ] Selection box is inconsistent and weird when dragging stuff around (happens when panning and zooming)
- [ ] Vertical mode just doesn't work at all really
- [x] Dragging objects doesn't show a "ghost" from being dragged and seems confusing
- [ ] Also dragging objects causes a vertical scroll which is annoying

**Comment by TGCrystal** [comment]
I can't seem to reproduce the first or fifth. The fourth has been implemented.
Not sure what exactly is meant by the third, but I think #891 fixes it
