### ISSUE TITLE
OR gate SVG rendering

### ISSUE THREAD

**Issue by Robert-Hammond** [OpenCircuits/OpenCircuits#508]
**Describe the bug**

**To Reproduce**
1. Open a Chrome browser
2. Go to http://www.opencircuits.io/img/icons/gates/orgate.svg
3. See that the lower left corner isn't rendering the complete sharp corner
4. Try zooming in, and the corner becomes rounded but still not correct

**Expected behavior**
Both corners should be sharp and perfectly mirrored.

**Screenshots**
![corner_render_bug](https://user-images.githubusercontent.com/53544605/75075910-df9ea880-54cc-11ea-9a66-b2ebe3e79020.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [79.0.3945.130]

**Comment by LeonMontealegre** [comment]
Fixed!
