### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#509]
**Describe the bug**
Dragging around duplicated objects doesn't move the objects and causes weird behavior with the selection box

**To Reproduce**
1. Go to opencircuits.io
2. Place a switch and LED
3. Connect the switch to the LED
4. Select the switch + LED
5. Press CTRL+D to duplicate
6. Click and drag on one of the duplicated objects
7. Notice that the object's don't move and other weird stuff happens

**Expected behavior**
Duplicated objects should be moveable

**Screenshots**
<img width="508" alt="Screen Shot 2020-02-28 at 4 27 37 PM" src="https://user-images.githubusercontent.com/29997057/75588755-4bda5880-5a47-11ea-891a-21a85a524449.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 80

**Additional context**
N/A

**Comment by Xystem4** [comment]
I believe this bug has been fixed. I can reproduce it on opencircuits.io but not the nightly build (or my local build).
