### ISSUE TITLE
Create IC from given logical expression

### ISSUE THREAD

**Issue by TGCrystal** [OpenCircuits/OpenCircuits#566]
**Is your feature request related to a problem? Please describe.**
Creating large and complex IC's is time consuming. Also, there is no quick feature to convert a logical expression to a circuit.

**Describe the solution you'd like**
A quick way to create an IC would be to enter a logical expression such as "!(p|q)&r". This would create an IC with inputs "p", "q", and "r" and output "output". The name of the IC would be the expression used to create it. The IC would store a circuit representation of the given expression. The creation of the IC would be done through a prompt that shows up when dragging an "Expression" option from the "Other" section of the component UI onto the screen.

**Describe alternatives you've considered**
The benefit of using an IC as opposed to a new component is that it would benefit from all the features that an IC has or will have later. For example, if issue #528 is implemented, this could be used to generate a truth table from a logical expression. 

**TODO**
 Create tests, there are lots of corner cases because of parenthesis to consider
Create the expression parser
Use the expression parser to generate an IC
Add something to the "other" section of the component list

**Comment by LeonMontealegre** [comment]
Design Doc:
https://docs.google.com/document/d/13S-Kk5zJVxIeX4MHnZ4gbLzvtfG0uNEYP8IE_SqObYk/edit?usp=sharing
