### ISSUE TITLE
Add "Information" button to components

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#576]
**Is your feature request related to a problem? Please describe.**
It can be very unclear what certain components do, or how they work. 

**Describe the solution you'd like**
On the selection popup for a single selected object type, there should be an "Information" button that when clicked, brings up documentation on that component.
For example, for the segment display, it should show a pin diagram of pins corresponding to which segment

**Comment by GarrettShorr** [comment]
Some options for implementation could be:

- On long hover, the info paragraph pops up
- A contextual menu item that says get info
- A help toggle button at the top of the screen that would change the cursor to a question mark that would make clicking on any component pop up the information
