### ISSUE TITLE
Rotating groups of components causes drift towards center of group

### ISSUE THREAD

**Issue by Xystem4** [OpenCircuits/OpenCircuits#595]
When rotating any group of components, all components will gradually drift towards the center of the red rotation circle (with and without shift being pressed), regardless of direction rotated. Undoing will undo the rotation, but not the drift towards the center.

Components before rotation:
![Before](https://user-images.githubusercontent.com/65842664/109373646-28c2ce80-787e-11eb-8e87-87b1c8f6a7f4.png)

Components after rotating, and then undoing rotation:
![After](https://user-images.githubusercontent.com/65842664/109373662-3710ea80-787e-11eb-9bd6-6253d0e0c701.png)

This has the add-on effect that when splitting a wire and then rotating a group of components that includes both original ends of the wire, the components will drift together. Then, when undoing, the rotation will be undone and so will the splitting of the wire, but the locations of the components will not be the same as when they began. Upon un-splitting, the wire will jump back to its original location prior to being split, which may no longer be connected to (or even near) the nodes it is meant to connect to. Note that this does not cause a crash or anything besides a visual error, which is fixed upon moving the wire itself or either component (or node) that it is connected to.

Disconnected wire:
![Disconnected wire](https://user-images.githubusercontent.com/65842664/109373558-80ad0580-787d-11eb-9e43-4f3c19cdd3af.png)

**Comment by LeonMontealegre** [comment]
This is probably partly due to #590, the camera offset probably causes the rotation math to be funky since it depends on the camera. Also sounds like the components `onTransformChange` might not be firing when undoing these actions

**Comment by LeonMontealegre** [comment]
It's not due to #590 :(

**Comment by LeonMontealegre** [comment]
I figured it out! Apparently, the midpoint of the objects are changing as they rotate (which shouldn't happen and I'm looking into that now), but so saving the original midpoint as a state variable `onActivate`, and using that consistent midpoint value fixes it.

**Comment by LeonMontealegre** [comment]
Got it! It's because
https://github.com/OpenCircuits/OpenCircuits/blob/0336e5f31b831a1685b5793336058d121dec0d28/src/app/core/tools/RotateTool.ts#L89

Is a LOOP! And on each iteration, only the first few objects have been moved; yet each time the selection's midpoint is recalculated! Meaning that it's not calculating correctly since not all objects have been moved!
