### ISSUE TITLE
Example Circuits broken

### ISSUE THREAD

**Issue by TGCrystal** [OpenCircuits/OpenCircuits#599]
**Describe the bug**
When clicking one of the example circuits to place it, the example circuit is not placed, and this sometime results in an error.

**To Reproduce**
1. Go to the latest version of the master branch
2. Click on the three line button in the top left
3. Click on any of the examples, then click ok to overwrite the scene
4. On Chrome on Windows, the circuits are not placed
5. On safari on iPhone 6s plus, an error is given for the AND gate and S-R Latch (screenshot below)

**Expected behavior**
The example circuit is placed 

**Screenshots**
![IMG_4464](https://user-images.githubusercontent.com/29614966/109378238-f1184e80-789e-11eb-9e04-3db5e931f0e5.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone 6s plus
 - OS: iOS 14.4
 - Browser safari

**Comment by LeonMontealegre** [comment]
It appears this is because example circuits are assumed to be "up-to-date" and the current set of examples are not. And since they are assumed to be "up-to-date" they're not being run through `VersionConflictResolver` to update it to the newest version.
