### ISSUE TITLE
Add panel showing history of actions

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#6]
Shows the history of actions in a way that could be "followed" in real life to make the circuit

**Comment by LeonMontealegre** [comment]
@GarrettShorr Can you clarify a bit how you envisioned this and how it could be useful?

**Comment by GarrettShorr** [comment]
Think of it like a photoshop or fusion360 history panel. It would let you jump back to any point in the build of the circuit and start building from that point. Basically it lets you see the steps you took in building it and lets you easily backtrack if you need to. 

Could maybe even have a playback feature that could be exported as a gif or something showing the building of the circuit.

**Comment by LeonMontealegre** [comment]
Closed from #933
