### ISSUE TITLE
Duplicated components staying powered with no power source

### ISSUE THREAD

**Issue by Xystem4** [OpenCircuits/OpenCircuits#613]
**Description**
When duplicating a component (or group of components), but _not_ the power source of the component(s), the copy will behave as if it is still being powered. This occurs when duplicating with ctrl+d, dragging and pressing space, and (on opencircuits.io where copy+paste still works) when using ctrl+c ctrl+v.

Updating a component stuck this way does not fix it. Moving it, changing where its output connects to, changing the number of inputs it takes, none stop it from staying powered. Only connecting a new power source and then removing it fixes it (or connecting an unpowered wire to the input port).

Note: this seems to affect each input port individually. Connecting an unpowered wire to an input port that thinks it is being powered will fix _that_ port, but any others will remain unchanged.

**To reproduce**
create a power source, and then one more more components taking power from it.
Select any amount of components receiving power to one or more input port, _without_ selecting the power source.
Duplicate the selected nodes

**Screenshot**
The entire top circuit was selected, except for the power source. It was then duplicated to form the other two circuits below. The bottom circuit then had one buffer deleted, updating the right half.
![duplicate bug](https://user-images.githubusercontent.com/65842664/110548868-3c342c00-80ff-11eb-86cf-dfe4d417f61f.png)

**Comment by TGCrystal** [comment]
Likely due to the same underlying issue as #468
