### ISSUE TITLE
Removing connected input port causes error

### ISSUE THREAD

**Issue by TGCrystal** [OpenCircuits/OpenCircuits#623]
**Describe the bug**
Increasing the number of inputs to a gate, connecting something to them, then decreasing the number of inputs causes an error.

**To Reproduce**
1. Go to nightly.opencircuits.io
2. Place a gate and a switch
3. Increase the number of inputs on the gate
4. Connect the switch to all of the gate's inputs
5. Decrease the number of inputs
6. There will be an error in the console, but when clicking off of the component the change will be reverted

**Screenshots**
![image](https://user-images.githubusercontent.com/29614966/112697624-5e97aa80-8e5e-11eb-93c5-1e26a49b1c34.png)

**Comment by Xystem4** [comment]
Unsurprisingly, this also happens when lowering the number of inputs on a segment display.
