### ISSUE TITLE
View IC not working

### ISSUE THREAD

**Issue by TGCrystal** [OpenCircuits/OpenCircuits#625]
**Describe the bug**
When clicking View IC the screen gets that gray effect that popups have but fails to actually show the IC

**To Reproduce**
1. Go to nightly.opencircuits.io
2. Create and connect a switch and LED, then create an IC with them
3. Click the IC, then click View IC

**Expected behavior**
The circuit used to create the IC will be displayed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by LeonMontealegre** [comment]
It appears that this is due to the fact that 90% of it is commented out!
