### ISSUE TITLE
Pressing escape to unfocus from text boxes

### ISSUE THREAD

**Issue by Xystem4** [OpenCircuits/OpenCircuits#632]
When selecting a component (or multiple components), the popup that appears contains a text box for the title and two textboxes for x and y positions. When focusing the cursor on one of these boxes, pressing the escape key should unfocus the cursor again (so that if the escape key is then pressed a second time, the component(s) will be deselected), similar to how pressing escape unfocuses the Color and Text Color input boxes.

**Comment by OwenMcGee** [comment]
This should also apply to the IC Name text field in the IC creation menu

**Comment by OwenMcGee** [comment]
This should also apply to the two size input fields in the Image Exporter menu
