### ISSUE TITLE
Renaming of ports not working

### ISSUE THREAD

**Issue by Xystem4** [OpenCircuits/OpenCircuits#651]
**Describe the bug**
When selecting one or more input/output nodes, a textbox no longer appears in the selection popup box

**To Reproduce**
1. Add any component to the canvas
2. Select one or more input/output node(s) from the component (note that you cannot click the node to select it, you must highlight it by dragging)
3. Observe that the popup box is empty, and contains no textbox

**Expected behavior**
We would expect the popup box to contain a textbox, and for editing it to display the new title next to that node

**Screenshots**
What it currently looks like selecting nodes:
![first](https://user-images.githubusercontent.com/65842664/116131162-0b518b80-a69a-11eb-97bc-4324ce3a6805.png)
What it looks like on opencircuits.io (has a textbox):
![second](https://user-images.githubusercontent.com/65842664/116131188-13113000-a69a-11eb-936e-5ebe1120c530.png)
What it would look like when the user changes the node names:
![third](https://user-images.githubusercontent.com/65842664/116131258-29b78700-a69a-11eb-9172-0a7dd18b36a0.png)
![fourth](https://user-images.githubusercontent.com/65842664/116131265-2b814a80-a69a-11eb-94c8-dc966d472f21.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Additional context**
There were several issues with this feature when it was still working, that would need to be addressed should it be fixed

**Comment by marcos-acosta** [comment]
Great catch!
