### ISSUE TITLE
Components Going Invisible when moving it towards the Edge of the site

### ISSUE THREAD

**Issue by qihenry** [OpenCircuits/OpenCircuits#655]
**Describe the bug**
When you move a component to the edge of the site, it will go invisible using the steps below. The component is still there as you can select it and move it, but it is not visible 

**To Reproduce**
1. Exit fullscreen
2. Add two components. The further apart they are, the easier it is to reproduce the bug 
3. Press f
4. Go back to fullscreen
5. Select a component and drag it to the right edge of the site
6. Bug seen

**Expected behavior**
The component should be visible at all time while it is on the canvas and within the user size

**Screenshots**
![realIssue](https://user-images.githubusercontent.com/24613817/116800123-32f68880-aacc-11eb-8733-3489cdd6beb3.gif)

**Desktop (please complete the following information):**
 - OS: Window 10 Education
 - Browser: Browser

**Additional context**
Don't zoom in or out after you press f. Also don't move the canvas. It works fine after those changes

**Comment by LeonMontealegre** [comment]
Probably related to Camera Resizing incorrectly, which is found `src/site/pages/digital/src/containers/MainDesigner/index.tsx` around lines 47-50.
Also related to `useWindowSize()` on line 41 probably
