### ISSUE TITLE
ItemNav Tab is too far right

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#682]
**Describe the bug**
The ItemNav tab to open/close the ItemNav is off of the left-side of the screen

**Screenshots**
<img width="503" alt="Screen Shot 2021-07-23 at 11 12 24 AM" src="https://user-images.githubusercontent.com/29997057/126824014-ccf6b84d-73b1-40f9-a059-cde1afeceb6e.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 91.0.4472.164

**Comment by TGCrystal** [comment]
That's odd, I had the opposite issue in #664 which was addressed in the unmerged pr #666

**Comment by SamooMei** [comment]
I tested this and found that this issue was indirectly solved by PR #666 but i'm not completely sure.
