### ISSUE TITLE
Strange behavior when holding down F key

### ISSUE THREAD

**Issue by OwenMcGee** [OpenCircuits/OpenCircuits#705]
**Describe the bug**
When zooming and holding F, the screen will jitter back and forth, and while panning the screen will wait until after the pan and then immediately snap back. Neither of these two behaviors are unexpected given that you can hold down the F key, but I think being able to hold down the F key (and get results) is itself unexpected.

**To Reproduce**
1. Open a new canvas
2. Hold down the F key
3. Zoom in or out (without letting go of F), and observe the screen stuttering

**Expected behavior**
I would have expected the F key to only have an effect when first pressed, and for holding it down further to do nothing.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Comment by LeonMontealegre** [comment]
Yeah this issue is more "Holding the F key creates multiple focus actions, should instead only do it on first press a single time"
