### ISSUE TITLE
Copy/Paste duplicates ICData

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#712]
**Describe the bug**
Copying then pasting an IC duplicates its ICData on the ItemNav

**To Reproduce**
1. Go to OpenCircuits
2. Load AND Gate example circuit or any other circuit that can turn into an IC
3. Select the circuit and create an IC
4. Copy the IC with CTRL+C
5. Paste the IC with CTRL+V
6. Notice that in the ItemNav, there are now 2 instances of the ICData

**Expected behavior**
Pasting ICs that have identical features shouldn't duplicate them

**Additional context**
The solution here should be entirely fixable within [`DigitalPaste`](https://github.com/OpenCircuits/OpenCircuits/blob/master/src/site/pages/digital/src/utils/DigitalPaste.ts). What needs to happen is we need to check if the incoming ICData from the paste-data is identical in structure to any of the existing ICDatas within `designer`.
This will require some function called like `ICDataEqual(ic1, ic2)` that will manually have to check if they are identical. Could potentially use serialeazy to serialize them and check if they are identical strings, but that might have problems if there's a reference to the `CircuitDesigner`.

**Comment by OwenMcGee** [comment]
I'll add that this only happens when using copy paste, and does _not_ happen when duplicating (translating+space or ctrl+d)
