### ISSUE TITLE
OpenCircuits Docs Privacy Error

### ISSUE THREAD

**Issue by T-Boya** [OpenCircuits/OpenCircuits#729]
**Describe the bug**
When navigating to docs.opencircuits.io in Chrome, the user is presented with a warning screen that their connection is not private and that 'Attackers might be trying to steal [their] information'

**To Reproduce**
1. Download and install google chrome
2.  Navigate to https://docs.opencircuits.io/ in chrome

**Expected behavior**
Following the above steps, you will see the warning screen shown below, ideally it would not be there

**Screenshots**
![RCOS](https://user-images.githubusercontent.com/36156355/135686539-482060d3-e7d6-4285-92a4-eea99ed4a696.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 94.0.4606.61

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus
 - OS: iOS 14.2
 - Browser: Chrome
 - Version: 93.0.4577.78

*PLEASE MAKE SURE TO APPROPRIATELY LABEL YOUR ISSUE, YOUR ISSUE IS REQUIRED TO SPECIFY AT LEAST A GENERAL IDEA OF:
Area: Backend
Difficulty: D1
Priority: P2
Scope: S1

**Comment by LeonMontealegre** [comment]
Should be fixed!
