### ISSUE TITLE
Add link to documentation site

### ISSUE THREAD

**Issue by TGCrystal** [OpenCircuits/OpenCircuits#736]
**Is your feature request related to a problem? Please describe.**
As far as I can see, there is no link from nightly.opencircuits.io to docs.opencircuits.io

**Describe the solution you'd like**
A link could easily be added to the help dropdown (shown below)
![image](https://user-images.githubusercontent.com/29614966/135701472-ad5e45fd-7b90-47f8-8037-a9a659de3559.png)

**Comment by aakhtar3** [comment]
I can work on this.
