### ISSUE TITLE
Undo malfunctioning

### ISSUE THREAD

**Issue by BaiTueeChuan** [OpenCircuits/OpenCircuits#740]
**Describe the bug**
When you connet two things, if you move one element somewhere else, undo button will not reset the moved element back to
its original position.

**To Reproduce**
1. create two random elements
2. connect them
3. move one of them randomly
4. click undo button
5. see error

**Expected behavior**
put the moved parts back to original position

**Comment by OwenMcGee** [comment]
I believe this actually _does_ move components back to their proper locations, it just doesn't update the canvas until the cursor is back over the canvas (which is as of yet an undocumented issue, I believe). Related to #647 I believe
