### ISSUE TITLE
Status Bar/Messages on Loading Screen

### ISSUE THREAD

**Issue by TGCrystal** [OpenCircuits/OpenCircuits#750]
Adding a loading progress bar to the loading screen would help to indicate to users (particularly those with slow internet connections or computers) that the site is indeed being loaded and not just looping forever.
Adding loading status messages could also be used to help debug issues if the site is actually stuck loading.

**Comment by LeonMontealegre** [comment]
Actually yeah this is super important, especially because a lot of time there's an error in the loading-process and the screen will just be stuck forever
