### ISSUE TITLE
Infinite D-flip-flop loop

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#77]
Creating a D-flipflop 
[DFlipFlop.txt](https://github.com/LeonMontealegre/OpenCircuits/files/1838350/DFlipFlop.txt)

And either loading it or putting it into a different context (ex. IC creator) causes an infinite loop that is very bad.

**Comment by nprisament** [comment]
I don't think this is still a problem, if it is, I am not sure how to recreate it

**Comment by LeonMontealegre** [comment]
I believe it is fixed so that's pretty cool.
Made the old file be load-able via #230
