### ISSUE TITLE
Ctrl+Z undoes title for circuit as well

### ISSUE THREAD

**Issue by mercuryhg31** [OpenCircuits/OpenCircuits#817]
**Describe the bug**
When using Ctrl+Z to undo, any named circuit will undo the circuit name as well. This does not happen with the manual undo button in the Component menu. (I'd guess this occurs with Cmd+Z as well, but I don't have a Mac.)

**To Reproduce**
1. Name the circuit
2. Perform a bunch of undoable actions
3. Ctrl+Z

**Expected behavior**
Ctrl+Z should not affect the title of the circuit at all, simply the actions in the circuit.

**Screenshots**
![2021-10-29-16-17-35](https://user-images.githubusercontent.com/26150304/139497255-c621dd69-5728-4b40-9e3f-47899db85587.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by BaiTueeChuan** [comment]
We just need to prevent default Z key and Y key function and  I believe that this bug was solved by pull request#744 .
