### ISSUE TITLE
Input issue on Firefox

### ISSUE THREAD

**Issue by RussellABH** [OpenCircuits/OpenCircuits#818]
**Describe the bug**
When you bring in any gate on Firefox, increase the input count, and then increase the input count on another gate the first change will be undone. Happens with any type of gate and combination of gate. This makes OpenCircuits really hard to use.

**To Reproduce**
1. Open Firefox
2. Bring in any two+ gates
3. Increase the input count of one
4. Increase input count of another
5. Note that the first change got undone

**Expected behavior**
It should not undo changes.

**Screenshots**
https://user-images.githubusercontent.com/75578919/139497651-fe625fb3-9d38-4254-bf30-789298539426.mp4

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox 93.0 (most recent as of this issue being made)

**Comment by ml619** [comment]
This issue does not occur in Safari, Chrome, Brave, and Opera
