### ISSUE TITLE
fit to screen breaks when selected component goes off screen

### ISSUE THREAD

**Issue by Kevin-771** [OpenCircuits/OpenCircuits#855]
**Describe the bug**
When a selected component goes off-screen, and then press f-key to fit-to-screen, the site bugs out.

**To Reproduce**
1. Go to https://nightly.opencircuits.io
2. Place component on the canvas
![Screenshot (8)](https://user-images.githubusercontent.com/70790256/140581640-b52867da-833d-480a-a8e3-c3d369a60ec4.png)
2. Edit coordinates (only bugs out for large positive values) so that component goes off-screen
![Screenshot (9)](https://user-images.githubusercontent.com/70790256/140581684-906ff928-5bb0-4d84-b685-fbcb3629fd8a.png)
3. Press f-key to fit-to-screen
4. Observe that everything breaks
![Screenshot (10)](https://user-images.githubusercontent.com/70790256/140581712-645917a9-6ba1-4f31-beb0-70c0f565e6a1.png)

**Expected behavior**
What should happen is that when you press the f-key, the screen should fit to the selected components.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by LeonMontealegre** [comment]
I can't appear to reproduce this anymore
