### ISSUE TITLE
Selection box interferes with tap to multicreate feature

### ISSUE THREAD

**Issue by TGCrystal** [OpenCircuits/OpenCircuits#863]
**Describe the bug**
When using the tap to place feature and dragging to create a selection at the same time, sometimes the selection action causes the component to not be placed.

**To Reproduce**
1. Go to [nightly.opencircuits.io](https://nightly.opencircuits.io/)
2. Drag a component to the canvas.
3. Tap a component in the item nav multiple times
4. Click and drag on the canvas, releasing while hovering over the previously placed component.

**Expected behavior**
The components should be placed and ideally the selection box should not be created while items are in the tap to place queue.

**Screenshots**
Example of components not being placed:
![tapNotCreate](https://user-images.githubusercontent.com/29614966/140629172-fcfb97dd-ff3a-42a0-9aa5-42f4b3b4d235.gif)
Example of components sometimes being placed:
![tapCreate](https://user-images.githubusercontent.com/29614966/140629196-e0036c34-c839-4d37-b89f-f54fb3ca4e61.gif)

**Comment by LeonMontealegre** [comment]
Probably due to cursor stopping over SelectionPopup
