### ISSUE TITLE
Add ability to input RGB/HEX/more? values for color picking

### ISSUE THREAD

**Issue by mercuryhg31** [OpenCircuits/OpenCircuits#873]
We should be able to pick colors for wires, LEDs, etc by inputting RGB/etc values to allow for people to make different things the exact same value.

**Additional context**
I may have made this suggestion because I was messing with someone by doing my best to make an unpowered wire the same color as the powered color.

**Comment by LeonMontealegre** [comment]
So color pickers are **entirely** browser dependent, meaning we would have to make our entire own color picker or find an existing library that implements one in React (the better option). But this is extremely low priority in my eyes
