### ISSUE TITLE
Pressing enter while the circuit title is in focus results in small error

### ISSUE THREAD

**Issue by OwenMcGee** [OpenCircuits/OpenCircuits#878]
**Describe the bug**
When the user has the circuit title input field in focus, if they press the enter key a small warning pops up next to the circuit title (although it does actually properly de-select the input field, despite this).

**To Reproduce**
1. Create a new circuit
2. Click into the circuit title input field
3. Press enter
4. Observe warning to the right of the input field

**Expected behavior**
I would expect pressing enter to simply deselect the input field, without producing a warning.

**Screenshots**
The warning:
![warning](https://user-images.githubusercontent.com/87297165/141010264-738f9883-50c5-412b-a1cd-5e318b373c17.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
Pressing escape has no effect (neither de-selects the input field, nor produces a warning).

The text of the warning is "Error occurred while saving: TypeError: Cannot read properties of undefined (reading 'getType')

**Comment by LeonMontealegre** [comment]
I believe you just don't have the backend running since pressing space in the Circuit Title calls a save
