### ISSUE TITLE
Press escape to cancel creation of a wire

### ISSUE THREAD

**Issue by OwenMcGee** [OpenCircuits/OpenCircuits#898]
When clicking an input port or an output port, a wire forms with one end attached to the port and the other following the user's cursor. If the user decides to cancel the creation of this new wire though, the only option is to click somewhere empty on the canvas. I would suggest that pressing escape should also cancel the creation of this wire, similar to how currently pressing escape de-selects components.

**Comment by LeonMontealegre** [comment]
Similarly, right-clicking should probably cancel it too
