### ISSUE TITLE
Add option to include labels when creating a circuit from a boolean expression

### ISSUE THREAD

**Issue by OwenMcGee** [OpenCircuits/OpenCircuits#909]
When using the expression to circuit feature, all inputs are already labelled by necessity in the expression, and it could be helpful to the user to display a label next to the switches (or buttons or clocks) when they appear on the canvas. A checkbox asking "Add labels next to inputs?" on the righthand side would be sufficient.

If the "Generate into IC" option is checked, ~this checkbox should probably be forced to be off, since the inputs are already visibly labelled~ these labels should be generated for the _internal_ circuit, but not placed on the canvas directly. That is, when choosing "View IC" on the resulting IC, the circuit that appears should have the labels.

**Comment by TGCrystal** [comment]
I like the suggestion, although I'm not sure if I agree that the option should be forced off for ICs. The labels can be useful to see when viewing the contents of the IC.

**Comment by OwenMcGee** [comment]
> I like the suggestion, although I'm not sure if I agree that the option should be forced off for ICs. The labels can be useful to see when viewing the contents of the IC.

That's a good point, I suppose I'd been thinking if the option was on while the ICs option was on, it would be making the labels _outside_ the IC. I'd definitely be in favor for it making the labels appear when viewing the IC, editing the original suggestion to reflect this
