### ISSUE TITLE
Jest code coverage

### ISSUE THREAD

**Issue by pbabell** [OpenCircuits/OpenCircuits#918]
**Is your feature request related to a problem? Please describe.**
When implementing a new feature or fixing a bug, it is helpful to know that new lines and branches are adequately tested. Without this knowledge, anyone reviewing the pull request will need to (or should) determine that the new code has adequate test coverage. Code coverage reports will improve code base robustness.

**Describe the solution you'd like**
Jest can provide code coverage reports as part of branch builds. Add a requirement for minimum new code and branch coverage. Also consider just displaying the reports and adding coverage as a requirement later.

**Comment by pbabell** [comment]
Can not edit labels for some reason.. Should be under devops

**Comment by TGCrystal** [comment]
This could be added in a `yarn coverage` command, similar to `yarn test`.

**Comment by LeonMontealegre** [comment]
> Can not edit labels for some reason.. Should be under devops

Allowing non-members to edit labels would allow them to edit labels for all issues which I think you can see how that would be a problem. Are you able to set them when creating an issue?

**Comment by pbabell** [comment]
Nope, had to leave all defaults
