### ISSUE TITLE
Clicking on Component Doesn't Allow Popup Interaction

### ISSUE THREAD

**Issue by riedee** [OpenCircuits/OpenCircuits#929]
**Describe the bug**
If you place any of the components and click into it to change the inputs, change the position, etc., you're unable to interact or change anything. As a note, when using the group select this bug doesn't appear, and sometimes if you hover over where the buttons should be it will fix itself.

**To Reproduce**
1. Go to https://nightly.opencircuits.io/ 
2. Click on any input, output, logic gate, flip flop, latch, or other component
3. Click on the component so you open the options menu
4. See how none of the usual buttons are showing and you're unable to update inputs, change position, etc. Nothing is interactable unless you drag to select.

**Expected behavior**
The popup when clicking components should be interactable and show its usual buttons.

**Screenshots**
![bug1 (3)](https://user-images.githubusercontent.com/65261267/144674218-6798825c-1774-449c-8580-772e419a114e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by TGCrystal** [comment]
Closed by #942
