### ISSUE TITLE
Cookies to save circuit

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#93]

**Comment by Darokrithia** [comment]
I think it should just load up whatever circuit they had open last.  Would be rather convenient if you somehow close a tab with a large unsaved circuit.

**Comment by LeonMontealegre** [comment]
At the moment there is a "Are you sure you want to exit" popup which removes the ability to accidentally close out of their unsaved circuit.
Similar to https://www.desmos.com/calculator

**Comment by Darokrithia** [comment]
Still might be convenient.  Other than that, if we use a database to save I don't see the need for cookies.
