### ISSUE TITLE
History Box: Optionally displayed extra information

### ISSUE THREAD

**Issue by TGCrystal** [OpenCircuits/OpenCircuits#976]
Some actions, like moving a component, do not display many details in the history box. Information such as what is being moved and where to/from it is being moved are stored in the action and could thus also be displayed in the history box.

Information like this can get quite detailed and clutter up the box quickly. Thus, whatever is implemented in #975 for group actions to be collapsible should also be useable to hide this information, and probably hide it by default.

**Comment by jssunray34** [comment]
Below are common actions that do not display many details in the history box:

- Move Object (Translate Action)
- Shift Object (Shift Action)
- Rotate (Rotate Action)

Below is additional optional information that could be displayed in the history box:

- What objects are being moved/shifted/rotated
- Translate Action: starting and ending positions for each object involved in the translation (`initialPositions` and `targetPositions`)
- Shift Action: shift amount (`i`)
- Rotate Action: initial and final angles for each object involved in the rotation (`initialAngles` and `finalAngles`)
