### ISSUE TITLE
History Box: Add another way to open the history box

### ISSUE THREAD

**Issue by TGCrystal** [OpenCircuits/OpenCircuits#979]
The history box currently can be opened only through a button in the itemnav. The history box also is not closed when the circuit is locked (which is the correct, intended behavior).
Those two facts cause a weird incongruity in that it is not possible to open the history box while the circuit is locked, even though it is allowed.
There should be another button somewhere else (probably either the header or the sidenav) to open the history box to correct this.

**Comment by EricW123** [comment]
Added New Button at top left corner #971
