### ISSUE TITLE
Mux and Demux missing input/output label

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#990]
The Multiplexer component should have a label for its output port, `O0`
and the Demux should have a label for its input port `I0`

Muxs currently:
![Screen Shot 2022-02-11 at 2 18 45 PM](https://user-images.githubusercontent.com/29997057/153655643-c484a16a-8f2a-4487-afc5-f893c27e35a9.png)

I would be okay with having it just be `O` and `I`, but we should discuss it... @TGCrystal ?

**Comment by TGCrystal** [comment]
I think that approach makes sense.
